# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # cache             
      - name: Cache
        uses: actions/cache@v4.2.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: ~/.npm
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
          # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies     
      - uses: actions/setup-node@v4
        with:
          node-version: 20
       - run: npm ci
       - run: npm test
      - name: Build and run app
         env:
           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
         run: node app.js



  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
